# Generated by Django 4.1.5 on 2023-06-12 06:56

from django.db import migrations, models
import max.models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='withoutvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('time_in', models.TimeField(default=max.models.get_current_time)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('today', models.DateField(auto_now_add=True)),
                ('time_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='withvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_registration', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('security_guard_name', models.CharField(max_length=100)),
                ('time_in', models.TimeField(default=max.models.get_current_time)),
                ('time_out', models.TimeField(null=True)),
                ('today', models.DateField(auto_now_add=True)),
                ('time_updated', models.BooleanField(default=False)),
            ],
        ),
    ]
