# Generated by Django 4.2.2 on 2023-06-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0003_guard_groups_guard_is_superuser_guard_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='guard',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='guard',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='guard',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='guard',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
