# Generated by Django 4.2.2 on 2023-06-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0005_customuser_customuserpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='CustomUserPermission',
        ),
    ]
