# Generated by Django 4.2.2 on 2023-06-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0006_remove_customuserpermission_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guard',
        ),
    ]
