# Generated by Django 4.2.2 on 2023-06-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0008_remove_withvehicle_security_guard_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withoutvehicle',
            name='id_photo',
        ),
        migrations.AddField(
            model_name='withoutvehicle',
            name='id_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
