# Generated by Django 4.2.2 on 2023-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0009_remove_withoutvehicle_id_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withoutvehicle',
            old_name='id_picture',
            new_name='id_picture_front',
        ),
        migrations.AddField(
            model_name='withvehicle',
            name='id_picture_back',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='withvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
