# Generated by Django 4.2.2 on 2023-06-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0010_rename_id_picture_withoutvehicle_id_picture_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withoutvehicle',
            old_name='id_picture_front',
            new_name='id_picture',
        ),
    ]
