# Generated by Django 4.1.5 on 2023-07-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0011_rename_id_picture_front_withoutvehicle_id_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_back',
            field=models.ImageField(null=True, upload_to='id_pictures/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to='id_pictures/'),
        ),
    ]
