# Generated by Django 4.1.5 on 2023-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0012_alter_withvehicle_id_picture_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_back',
            field=models.ImageField(null=True, upload_to='withvehicle/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to='withvehicle/'),
        ),
    ]
