# Generated by Django 4.1.5 on 2023-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0014_alter_withvehicle_id_picture_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='id_picture',
            field=models.ImageField(null=True, upload_to='without_vehicle_pictures/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_back',
            field=models.ImageField(null=True, upload_to='with_vehicle_pictures/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to='with_vehicle_pictures/'),
        ),
    ]
