# Generated by Django 4.2.2 on 2023-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0015_alter_withoutvehicle_id_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='id_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_back',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
