# Generated by Django 4.2.2 on 2023-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0017_remove_withvehicle_id_picture_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withoutvehicle',
            old_name='id_picture',
            new_name='id_picture_front',
        ),
    ]
