# Generated by Django 4.2.2 on 2023-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0018_rename_id_picture_withoutvehicle_id_picture_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='withvehicle',
            name='id_picture_front1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='withvehicle',
            name='id_picture_front2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
