# Generated by Django 4.1.5 on 2023-07-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0019_withvehicle_id_picture_front1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='id_picture_front',
            field=models.ImageField(upload_to='images'),
        ),
    ]
