# Generated by Django 4.1.5 on 2023-07-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0025_alter_withoutvehicle_id_picture_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
