# Generated by Django 4.1.5 on 2023-07-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0026_alter_withoutvehicle_id_picture_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withvehicle',
            old_name='id_picture_front2',
            new_name='vehice_photo',
        ),
    ]
