# Generated by Django 4.1.5 on 2023-07-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0028_rename_vehice_photo_withvehicle_id_picture_front2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='id_picture_front',
            field=models.ImageField(null=True, upload_to='Idphotowithoutvehicle/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front1',
            field=models.ImageField(null=True, upload_to='IDphotowithvehicle/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front2',
            field=models.ImageField(null=True, upload_to='Vehiclephoto/'),
        ),
    ]
