# Generated by Django 4.2.3 on 2023-07-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0029_alter_withoutvehicle_id_picture_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withoutvehicle',
            name='id_picture_front',
            field=models.ImageField(blank=True, null=True, upload_to='Idphotowithoutvehicle/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front1',
            field=models.ImageField(blank=True, null=True, upload_to='IDphotowithvehicle/'),
        ),
        migrations.AlterField(
            model_name='withvehicle',
            name='id_picture_front2',
            field=models.ImageField(blank=True, null=True, upload_to='Vehiclephoto/'),
        ),
    ]
